# Generated by Django 3.1.6 on 2021-02-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210208_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skidb',
            name='Availability',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='skidb',
            name='Brand',
            field=models.CharField(default='', max_length=200),
        ),
    ]
