# Generated by Django 3.1.6 on 2021-02-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSectionsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sections', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SkiBootsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Size', models.IntegerField(max_length=200)),
                ('Availability', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SkiDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Size', models.IntegerField(max_length=200)),
                ('Availability', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SnowboardBootsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Size', models.IntegerField(max_length=200)),
                ('Availability', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SnowboardDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Size', models.IntegerField(max_length=200)),
                ('Availability', models.IntegerField(max_length=200)),
            ],
        ),
    ]
